[project]
name = "datacommons-cli"
dynamic = ["version"]
description = 'Data Commons CLI'
license = "Apache-2.0"
readme = "README.md"

requires-python = ">=3.11"
keywords = []
authors = []
dependencies = [
  "click>=8.1.7",
  "datacommons-api",
  "datacommons-db",
  "datacommons-schema",
]
urls = {Homepage = "https://github.com/datacommonsorg/datacommons"}

[project.scripts]
datacommons = "datacommons_cli.cli:cli"

[build-system]
requires = ["uv", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "datacommons_cli.version.__version__"}
